name: llamauav
channels:
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - cuda=11.8.0=0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-demo-suite=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - expat=2.7.1=h6a678d5_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.4.0.31=0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2022.3.0.22=0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.21.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - airsim==1.8.1
      - altair==5.5.0
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==24.3.0
      - bitsandbytes==0.41.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cmake==3.25.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - decord==0.6.0
      - deepspeed==0.9.5
      - defusedxml==0.7.1
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - exceptiongroup==1.2.2
      - fairscale==0.4.13
      - fastapi==0.115.6
      - ffmpy==0.5.0
      - filelock==3.13.1
      - flash-attn==2.5.9.post1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==3.35.2
      - gradio-client==0.2.9
      - h11==0.14.0
      - hf-xet==1.1.8
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.27.1
      - idna==3.4
      - jinja2==3.1.3
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - latex2mathml==3.77.0
      - linkify-it-py==2.0.3
      - lit==15.0.7
      - llamavid==1.0
      - llava==1.1.1
      - llvmlite==0.43.0
      - markdown-it-py==2.2.0
      - markdown2==2.5.2
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - narwhals==1.21.1
      - networkx==3.2.1
      - ninja==1.11.1.3
      - numba==0.60.0
      - numpy==1.26.3
      - openai==1.59.5
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - orjson==3.10.13
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.4.0
      - pillow==10.2.0
      - platformdirs==4.3.6
      - propcache==0.2.1
      - protobuf==5.29.2
      - psutil==6.1.1
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.8
      - pydantic==1.10.20
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.28.1
      - rpds-py==0.22.3
      - safetensors==0.5.1
      - scikit-learn==1.2.2
      - scipy==1.15.0
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.41.3
      - supervision==0.25.1
      - svgwrite==1.4.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - timm==0.6.13
      - tokenizers==0.13.3
      - tomli==2.2.1
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tornado==4.5.3
      - tqdm==4.67.1
      - transformers==4.31.0
      - triton==2.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - urllib3==1.26.13
      - uvicorn==0.34.0
      - wandb==0.18.7
      - wavedrom==2.0.3.post3
      - websockets==14.1
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.18.3
