name: vln_proj
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
  - pytorch3d
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cffi=1.17.1
  - colorama=0.4.6
  - cpython=3.10.19
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dataclasses=0.8
  - expat=2.7.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - iopath=0.1.10
  - jbig=2.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.44
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.10
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.43
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.6
  - ocl-icd=2.3.2
  - olefile=0.47
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.5.4
  - pip=25.2
  - pthread-stubs=0.3
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytorch3d=0.7.8
  - readline=8.3
  - sqlite=3.50.2
  - sympy=1.14.0
  - tbb=2021.5.0
  - tk=8.6.15
  - torchaudio=2.2.0
  - torchtriton=2.2.0
  - torchvision=0.17.0
  - tqdm=4.67.1
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.2
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - array-record==0.7.1
      - asciitree==0.3.3
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - bokeh==3.7.2
      - cachetools==5.5.2
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==0.29.28
      - dash==3.0.3
      - datasets==4.3.0
      - decorator==5.2.1
      - dill==0.4.0
      - dlimp==0.0.1
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - draccus==0.10.0
      - easydict==1.13
      - einops==0.8.0
      - etils==1.12.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - flask==3.0.3
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - ftfy==6.3.0
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.39.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - gymnasium==1.0.0
      - h11==0.16.0
      - h5py==3.13.0
      - hf-transfer==0.1.9
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.26.5
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.23.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipdb==0.13.13
      - ipython==8.35.0
      - ipywidgets==8.1.6
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - json-numpy==2.1.1
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.14
      - keras==2.15.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - lightning==2.4.0
      - lightning-utilities==0.14.3
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - ml-dtypes==0.2.0
      - moviepy==2.1.2
      - msgpack==1.1.0
      - multidict==6.4.3
      - multimethod==1.12
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - narwhals==1.35.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.10.2.3
      - numcodecs==0.13.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - openexr==3.3.3
      - openvla==0.0.3
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - peft==0.11.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - platformdirs==4.3.7
      - plotly==6.0.1
      - pooch==1.8.2
      - portalocker==3.1.1
      - proglog==0.1.11
      - promise==2.3
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==4.21.12
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pyrep==4.1.0.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pyvista==0.44.2
      - pyyaml==6.0.2
      - pyyaml-include==1.4.1
      - rdkit==2024.9.6
      - referencing==0.36.2
      - regex==2024.9.11
      - requests==2.32.2
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.7.1
      - rlbench==1.2.0
      - rpds-py==0.24.0
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scooby==0.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.26.1
      - setproctitle==1.3.5
      - setuptools==59.5.0
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.15.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.1
      - termcolor==2.4.0
      - threadpoolctl==3.6.0
      - timm==0.9.10
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.2.1
      - torch-geometric==2.6.1
      - torchmetrics==1.7.1
      - tornado==6.4.2
      - traitlets==5.14.3
      - transformers==4.40.1
      - trimesh==4.6.6
      - triton==3.0.0
      - typeguard==2.13.3
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==1.26.13
      - vtk==9.3.1
      - wandb==0.19.0
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wrapt==1.14.1
      - xxhash==3.6.0
      - xyzservices==2025.1.0
      - yarl==1.19.0
      - zarr==2.18.3
      - zipp==3.21.0
prefix: /home/liusq/miniconda3/envs/vln_proj
